import{a as w,S as L,i as l}from"./assets/vendor-06b1bbdf.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function a(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=a(e);fetch(e.href,t)}})();async function m(r,o){const a="https://pixabay.com/api/",i="43257905-28a3b58ba6106b31a5e4f67d7",e=new URLSearchParams({key:i,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:15}),{data:t}=await w(`${a}?${e}`);return t}const g=document.querySelector(".gallery-nav");function p(r){const o=r.hits.map(({webformatURL:i,largeImageURL:e,tags:t,likes:n,views:y,comments:f,downloads:b})=>`
        <li class="gallery-item">
        <a class="gallery-link" href="${e}">
        <img 
        class="gallery-image"
        src="${i}"
        alt="${t}"/>
        <div class="image-information">
        <p>Likes: ${n}</p>
        <p>Views: ${y}</p>
        <p>Comments: ${f}</p>
        <p>Downloads: ${b}</p>
        </div>
        
        </a>
        </li>`).join("");g.insertAdjacentHTML("beforeend",o),new L(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const s=document.querySelector(".loader"),C=document.querySelector(".input-field"),u=document.querySelector(".js-load-more");u.addEventListener("click",v);C.addEventListener("submit",S);let h,d,c;u.classList.add("hidden");s.classList.replace("loader","hidden");async function S(r){if(r.preventDefault(),g.innerHTML="",s.classList.replace("hidden","loader"),d=r.target.elements.designation.value.trim(),c=1,d===""){s.classList.replace("loader","hidden"),l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"bottomCenter",iconColor:"white"});return}try{const o=await m(c,d);if(o.totalHits===0){s.classList.replace("loader","hidden"),l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"bottomCenter",iconColor:"white"});return}l.success({iconColor:"yellow",message:"Enjoy watching!",position:"topRight",backgroundColor:"blue",messageColor:"yellow"}),p(o)}catch{l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"bottomCenter",iconColor:"white"})}r.target.reset(),u.classList.replace("hidden","visible"),s.classList.replace("loader","hidden")}async function v(){c+=1;try{const a=await m(c,d);h=Math.ceil(a.totalHits/15),p(a),s.classList.replace("hidden","loader"),c>=h&&(s.classList.replace("loader","hidden"),u.classList.replace("visible","hidden"),l.show({message:"We`re sorry, but you've reached the end of search results.",messageColor:"white",backgroundColor:"green",position:"bottomCenter",iconColor:"white"}))}catch(a){alert(a.message)}const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:o*2,behavior:"smooth"}),s.classList.replace("loader","hidden")}
//# sourceMappingURL=commonHelpers.js.map
