import{a as w,S as C,i as l}from"./assets/vendor-06b1bbdf.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();async function m(s,o){const r="https://pixabay.com/api/",i="43257905-28a3b58ba6106b31a5e4f67d7",e=new URLSearchParams({key:i,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:15}),{data:t}=await w(`${r}?${e}`);return t}const g=document.querySelector(".gallery-nav");function p(s){const o=s.hits.map(({webformatURL:i,largeImageURL:e,tags:t,likes:n,views:y,comments:f,downloads:b})=>`
        <li class="gallery-item">
        <a class="gallery-link" href="${e}">
        <img 
        class="gallery-image"
        src="${i}"
        alt="${t}"/>
        <div class="image-information">
        <p>Likes: ${n}</p>
        <p>Views: ${y}</p>
        <p>Comments: ${f}</p>
        <p>Downloads: ${b}</p>
        </div>
        
        </a>
        </li>`).join("");g.insertAdjacentHTML("beforeend",o),new C(".gallery a",{captionsData:"alt",captionDelay:250}).refresh()}const a=document.querySelector(".loader"),L=document.querySelector(".input-field"),d=document.querySelector(".js-load-more");d.addEventListener("click",S);L.addEventListener("submit",v);let h,u,c;d.classList.add("hidden");a.classList.replace("loader","hidden");async function v(s){if(s.preventDefault(),g.innerHTML="",a.classList.replace("hidden","loader"),u=s.target.elements.designation.value.trim(),c=1,u===""){a.classList.replace("loader","hidden"),l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"bottomCenter",iconColor:"white"});return}try{const o=await m(c,u);if(o.totalHits===0){a.classList.replace("loader","hidden"),l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"bottomCenter",iconColor:"white"});return}else if(o.totalHits<15){a.classList.replace("loader","hidden"),d.classList.replace("visible","hidden"),l.show({message:"We`re sorry, but you've reached the end of search results.",messageColor:"white",backgroundColor:"green",position:"bottomCenter",iconColor:"white"});return}l.success({iconColor:"yellow",message:"Enjoy watching!",position:"topRight",backgroundColor:"blue",messageColor:"yellow"}),p(o)}catch{l.show({message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"white",backgroundColor:"red",position:"bottomCenter",iconColor:"white"})}s.target.reset(),d.classList.replace("hidden","visible"),a.classList.replace("loader","hidden")}async function S(){c+=1;try{const r=await m(c,u);h=Math.ceil(r.totalHits/15),console.log(r),p(r),a.classList.replace("hidden","loader"),c>=h&&(a.classList.replace("loader","hidden"),d.classList.replace("visible","hidden"),l.show({message:"We`re sorry, but you've reached the end of search results.",messageColor:"white",backgroundColor:"green",position:"bottomCenter",iconColor:"white"}))}catch(r){alert(r.message)}const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:o*2,behavior:"smooth"}),a.classList.replace("loader","hidden")}
//# sourceMappingURL=commonHelpers.js.map
